version: '3.8'

# start with containers
services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    restart: always
    labels:
      - traefik.http.routers.nginx.rule=Host(`demo-1.liefer.it`)
      - "traefik.http.routers.nginx.tls.certResolver=default"
      - "traefik.http.routers.nginx.tls=true"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - router

# free naming for the container and url
  db:
    image: mysql:5.7
    # with - is a list
    volumes:
    # host folder will be create automatic
      - ./wordpress/data/db/:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret123root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - router
#    log-driver: "json-file"
#      options:
#        max-file: 5
#        max-size: 10m

  wordpress:
# start time dependency
    depends_on:
      - db
    image: wordpress:${TAG}
# mapping to network
  # simpel to external network
  # 127.0.0.1: only in docker net
  # 10.0.0.<ip> company network
#    ports:
#      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
# entry folder for docker exec
    working_dir: /var/www/html
    volumes:
      - ./wordpress/data/wordpress:/var/www/html/wp-content
    labels:
      - traefik.http.routers.word.rule=Host(`word.demo-1.liefer.it`)
      - "traefik.http.routers.word.tls.certResolver=default"
      - "traefik.http.routers.word.tls=true"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - router
      
networks:
  router:
    external:
      name: router-network
