version: "3.8"
services:
  docs-dockers:
    build:
      context: ./docker-training/docs
      dockerfile: Dockerfile-dev
#    ports:
#      - 8080:8080

    restart: always
    labels:
     - traefik.http.routers.dockers.rule=Host(`docker.demo-1.liefer.it`)
     - "traefik.http.routers.dockers.tls.certResolver=default"
     - "traefik.http.routers.dockers.tls=true"
     - "com.centurylinklabs.watchtower.enable=true"
    networks:
     - router

  docs-kubernets:
#    image: docker.pkg.github.com/jamct/kubernetes-training/docs:latest
    build:
      context: ./kubernetes-training/docs
      dockerfile: Dockerfile-dev
 #   ports:
 #     - 8080:8080
    restart: always
    labels:
      - traefik.http.routers.kubers.rule=Host(`kubernets.demo-1.liefer.it`)
      - "traefik.http.routers.kubers.tls.certResolver=default"
      - "traefik.http.routers.kubers.tls=true"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - router
networks:
  router:
    external:
      name: router-network
